# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

user = User.new(username: "kurisu", password: "okabe", email: "kurisu@fgl.com")
user.reset_session_token
user.save!
animes = Anime.create!([
  {title: "Accel World", episode_count: 24, show_type: "TV"},
  {title: "Accel World EX", episode_count: 2, show_type: "OVA"},
  {title: "Afro Samurai", episode_count: 5, show_type: "TV"},
  {title: "Akira", episode_count: 1, show_type: "Movie"},
  {title: "Angel Beats", episode_count: 13, show_type: "TV"},
  {title: "Angelic Layer", episode_count: 26, show_type: "TV"},
  {title: "Baccano!", episode_count: 13, show_type: "TV"},
  {title: "Baccano! Specials", episode_count: 3, show_type: "TV"},
  {title: "Bakemonogatari", episode_count: 15, show_type: "TV"},
  {title: "Bartender", episode_count: 11, show_type: "TV"},
  {title: "Black Cat", episode_count: 23, show_type: "TV"},
  {title: "Black Lagoon", episode_count: 12, show_type: "TV"},
  {title: "Black Lagoon: The Second Barrage", episode_count: 12, show_type: "TV"},
  {title: "Black Rock Shooter (OVA)", episode_count: 1, show_type: "OVA"},
  {title: "Bleach: Memories of Nobody", episode_count: 1, show_type: "Movie"},
  {title: "Bleach: The DiamondDust Rebellion", episode_count: 1, show_type: "Movie"},
  {title: "Bleach: The Sealed Sword Frenzy", episode_count: 1, show_type: "Special"},
  {title: "Blood+", episode_count: 50, show_type: "Special"},
  {title: "Blood: The Last Vampire", episode_count: 1, show_type: "Movie"},
  {title: "Bounen no Xamdou", episode_count: 26, show_type: "ONA"},
  {title: "Byousoku 5 Centimeter", episode_count: 1, show_type: "Movie"},
  {title: "Code Geass: Boukoku no Akito", episode_count: 4, show_type: "Movie"},
  {title: "Code Geass: Hangyaku no Lelouch", episode_count: 25, show_type: "TV"},
  {title: "Code Geass: Hangyaku no Lelouch R2", episode_count: 25, show_type: "TV"},
  {title: "Code Geass: Nunnally in Wonderland", episode_count: 1, show_type: "OVA"},
  {title: "Cowboy Bebop", episode_count: 26, show_type: "TV"},
  {title: "Cross Game", episode_count: 50, show_type: "TV"},
  {title: "D.N.Angel", episode_count: 26, show_type: "TV"},
  {title: "Darker than Black: Kuro no Keiyakusha", episode_count: 25, show_type: "TV"},
  {title: "Darker than Black: Kuro no Keiyakusha Special", episode_count: 1, show_type: "Special"},
  {title: "Darker than Black: Ryuusei no Gemini", episode_count: 12, show_type: "TV"},
  {title: "Death Note", episode_count: 37, show_type: "TV"},
  {title: "Durarara!!", episode_count: 24, show_type: "TV"},
  {title: "Elfen Lied", episode_count: 13, show_type: "TV"},
  {title: "Elfen Lied Special", episode_count: 1, show_type: "Special"},
  {title: "Ergo Proxy", episode_count: 23, show_type: "TV"},
  {title: "Escaflowne", episode_count: 26, show_type: "TV"},
  {title: "Evangelion 1.0: You Are (Not) Alone", episode_count: 1, show_type: "Movie"},
  {title: "Evangelion 2.0: You Can (Not) Advance", episode_count: 1, show_type: "Movie"},
  {title: "Evangelion 3.0: You Can (Not) Redo", episode_count: 1, show_type: "Movie"},
  {title: "Eve no Jikan", episode_count: 6, show_type: "ONA"},
  {title: "Eve no Jikan (Movie)", episode_count: 1, show_type: "Movie"},
  {title: "Fate/stay night: Unlimited Blade Works", episode_count: 1, show_type: "Movie"},
  {title: "Final Fantasy VII: Advent Children", episode_count: 1, show_type: "Movie"},
  {title: "Final Fantasy VII: Advent Children Complete", episode_count: 1, show_type: "Movie"},
  {title: "FLCL", episode_count: 6, show_type: "OVA"},
  {title: "Fruits Basket", episode_count: 26, show_type: "TV"},
  {title: "Full Metal Panic!", episode_count: 24, show_type: "TV"},
  {title: "Full Metal Panic! The Second Raid", episode_count: 13, show_type: "TV"},
  {title: "Full Metal Panic? Fumoffu", episode_count: 12, show_type: "TV"},
  {title: "Fullmetal Alchemist", episode_count: 51, show_type: "TV"},
  {title: "Fullmetal Alchemist: Brotherhood", episode_count: 64, show_type: "TV"},
  {title: "Fullmetal Alchemist: Conqueror of Shamballa", episode_count: 1, show_type: "Movie"},
  {title: "Ga-Rei: Zero", episode_count: 12, show_type: "TV"},
  {title: "Gankutsuou: The Count of Monte Cristo", episode_count: 26, show_type: "TV"},
  {title: "Gantz", episode_count: 13, show_type: "TV"},
  {title: "Gantz 2nd Stage", episode_count: 13, show_type: "TV"},
  {title: "Ghost in the Shell", episode_count: 1, show_type: "Movie"},
  {title: "Ghost in the Shell 2.0", episode_count: 1, show_type: "Movie"},
  {title: "Goshuushou-sama Ninomiya-kun", episode_count: 12, show_type: "TV"},
  {title: "Great Teacher Onizuka", episode_count: 43, show_type: "TV"},
  {title: "Hachimitsu to Clover", episode_count: 24, show_type: "TV"},
  {title: "Hachimitsu to Clover II", episode_count: 12, show_type: "TV"},
  {title: "Hachimitsu to Clover Specials", episode_count: 2, show_type: "Special"},
  {title: "Hataraku Maou-sama!", episode_count: 13, show_type: "TV"},
  {title: "Hayate no Gotoku! Can't Take My Eyes Off You", episode_count: 12, show_type: "TV"},
  {title: "Hayate no Gotoku! Heaven Is a Place on Earth", episode_count: 1, show_type: "Movie"},
  {title: "Hayate no Gotoku!!", episode_count: 25, show_type: "TV"},
  {title: "Hayate no Gotoku!!: Atsu ga Natsuize - Mizugihen!", episode_count: 1, show_type: "OVA"},
  {title: "Hellsing", episode_count: 13, show_type: "TV"},
  {title: "Hellsing Ultimate", episode_count: 10, show_type: "OVA"},
  {title: "Hentai Ouji to Warawanai Neko.", episode_count: 12, show_type: "TV"},
  {title: "Higashi no Eden", episode_count: 11, show_type: "TV"},
  {title: "Higashi no Eden Movie I: The King of Eden", episode_count: 1, show_type: "Movie"},
  {title: "Higashi no Eden Movie II: Paradise Lost", episode_count: 1, show_type: "Movie"},
  {title: "High School DxD", episode_count: 12, show_type: "TV"},
  {title: "High School DxD OVA", episode_count: 2, show_type: "OVA"},
  {title: "High School DxD Specials", episode_count: 6, show_type: "Special"},
  {title: "Hikaru no Go", episode_count: 75, show_type: "TV"},
  {title: "Hikaru no Go: Journey to the North Star Cup", episode_count: 1, show_type: "Special"},
  {title: "Hikaru no Go: New Year Special", episode_count: 1, show_type: "Special"},
  {title: "Hoshi no Koe", episode_count: 1, show_type: "OVA"},
  {title: "Hoshi wo Ou Kodomo", episode_count: 1, show_type: "Movie"},
  {title: "Hotarubi no Mori e", episode_count: 1, show_type: "Movie"},
  {title: "Howl no Ugoku Shiro", episode_count: 1, show_type: "Movie"},
  {title: "Ikkitousen", episode_count: 13, show_type: "TV"},
  {title: "Inferno Cop", episode_count: 13, show_type: "ONA"},
  {title: "IS: Infinite Stratos", episode_count: 12, show_type: "TV"},
  {title: "IS: Infinite Stratos Encore: Koi ni Kogareru Sextet", episode_count: 1, show_type: "OVA"},
  {title: "Kaichou wa Maid-sama!", episode_count: 26, show_type: "TV"},
  {title: "Kakumeiki Valvrave", episode_count: 13, show_type: "TV"},
  {title: "Kanojo to Kanojo no Neko", episode_count: 1, show_type: "OVA"},
  {title: "Kashimashi: Girl Meets Girl", episode_count: 12, show_type: "TV"},
  {title: "Kashimashi: Girl Meets Girl OVA", episode_count: 1, show_type: "OVA"},
  {title: "Katanagatari", episode_count: 12, show_type: "TV"},
  {title: "Kaze no Tani no Nausicaa", episode_count: 1, show_type: "Movie"},
  {title: "Kampfer", episode_count: 12, show_type: "TV"},
  {title: "Kampfer fur die Liebe", episode_count: 2, show_type: "Special"},
  {title: "Kishin Taisen Gigantic Formula", episode_count: 26, show_type: "TV"},
  {title: "Kotonoha no Niwa", episode_count: 1, show_type: "Movie"},
  {title: "Kumo no Mukou, Yakusoku no Basho", episode_count: 1, show_type: "Movie"},
  {title: "Kuuchuu Buranko", episode_count: 11, show_type: "TV"},
  {title: "Le Chevalier D'Eon", episode_count: 24, show_type: "TV"},
  {title: "Love Hina", episode_count: 24, show_type: "TV"},
  {title: "Lucky Star", episode_count: 24, show_type: "TV"},
  {title: "Lucky Star: Original na Visual to Animation", episode_count: 1, show_type: "OVA"},
  {title: "Mahou Shoujo Lyrical Nanoha", episode_count: 13, show_type: "TV"},
  {title: "Mahou Shoujo Lyrical Nanoha A's", episode_count: 13, show_type: "TV"},
  {title: "Mahou Shoujo Lyrical Nanoha StrikerS", episode_count: 26, show_type: "TV"},
  {title: "Mahou Shoujo Lyrical Nanoha: The Movie 1st", episode_count: 1, show_type: "Movie"},
  {title: "Mahou Shoujo Lyrical Nanoha: The Movie 2nd A's", episode_count: 1, show_type: "Movie"},
  {title: "Mahou Shoujo Madoka Magica", episode_count: 12, show_type: "TV"},
  {title: "Mayo Chiki!", episode_count: 13, show_type: "TV"},
  {title: "Minami-ke", episode_count: 13, show_type: "TV"},
  {title: "MM!", episode_count: 12, show_type: "TV"},
  {title: "Mobile Suit Gundam 00", episode_count: 25, show_type: "TV"},
  {title: "Mobile Suit Gundam 00 Second Season", episode_count: 25, show_type: "TV"},
  {title: "Mobile Suit Gundam 00 The Movie: A Wakening of the Trailblazer", episode_count: 1, show_type: "Movie"},
  {title: "Mobile Suit Gundam Wing: Endless Waltz Movie", episode_count: 1, show_type: "Movie"},
  {title: "Mononoke Hime", episode_count: 1, show_type: "Movie"},
  {title: "Mushishi", episode_count: 26, show_type: "TV"},
  {title: "Naruto", episode_count: 220, show_type: "TV"},
  {title: "Nekomonogatari: Kuro", episode_count: 4, show_type: "TV"},
  {title: "Neon Genesis Evangelion", episode_count: 26, show_type: "TV"},
  {title: "Neon Genesis Evangelion: The End of Evangelion", episode_count: 1, show_type: "Movie"},
  {title: "NHK ni Youkoso!", episode_count: 24, show_type: "TV"},
  {title: "Night Wizard", episode_count: 13, show_type: "TV"},
  {title: "Nisemonogatari", episode_count: 11, show_type: "TV"},
  {title: "Nodame Cantabile", episode_count: 23, show_type: "TV"},
  {title: "Nodame Cantabile Paris Hen", episode_count: 11, show_type: "TV"},
  {title: "Nyan Koi!", episode_count: 12, show_type: "TV"},
  {title: "Onegai Teacher", episode_count: 12, show_type: "TV"},
  {title: "Onegai Twins", episode_count: 12, show_type: "TV"},
  {title: "Ookami Kodomo no Ame to Yuki", episode_count: 1, show_type: "Movie"},
  {title: "Ookami to Koushinryou", episode_count: 13, show_type: "TV"},
  {title: "Ookami to Koushinryou II", episode_count: 12, show_type: "TV"},
  {title: "Ore no Imouto ga Konnani Kawaii Wake ga Nai", episode_count: 12, show_type: "TV"},
  {title: "Ore no Imouto ga Konnani Kawaii Wake ga Nai Specials", episode_count: 4, show_type: "Special"},
  {title: "Ore no Imouto ga Konnani Kawaii Wake ga Nai.", episode_count: 13, show_type: "TV"},
  {title: "Ouran Koukou Host Club", episode_count: 26, show_type: "TV"},
  {title: "Pale Cocoon", episode_count: 1, show_type: "OVA"},
  {title: "Panty & Stocking with Garterbelt", episode_count: 13, show_type: "TV"},
  {title: "Perfect Blue", episode_count: 1, show_type: "Movie"},
  {title: "Piano no Mori", episode_count: 1, show_type: "Movie"},
  {title: "Prince of Tennis", episode_count: 178, show_type: "TV"},
  {title: "Prince of Tennis: The National Tournament", episode_count: 13, show_type: "OVA"},
  {title: "Prince of Tennis: The National Tournament Finals", episode_count: 7, show_type: "OVA"},
  {title: "Prince of Tennis: The National Tournament Semifinals", episode_count: 6, show_type: "OVA"},
  {title: "Rec", episode_count: 9, show_type: "TV"},
  {title: "Redline", episode_count: 1, show_type: "Movie"},
  {title: "Rurouni Kenshin: Meiji Kenkaku Romantan", episode_count: 94, show_type: "TV"},
  {title: "Rurouni Kenshin: Meiji Kenkaku Romantan - Seisou Hen", episode_count: 2, show_type: "OVA"},
  {title: "Rurouni Kenshin: Meiji Kenkaku Romantan - Tsuiokuhen", episode_count: 4, show_type: "OVA"},
  {title: "Samurai Champloo", episode_count: 26, show_type: "TV"},
  {title: "Samurai Deeper Kyo", episode_count: 26, show_type: "TV"},
  {title: "Seitokai no Ichizon", episode_count: 12, show_type: "TV"},
  {title: "Sen to Chihiro no Kamikakushi", episode_count: 1, show_type: "Movie"},
  {title: "Sengoku Basara", episode_count: 12, show_type: "TV"},
  {title: "Seto no Hanayome", episode_count: 26, show_type: "TV"},
  {title: "Shingetsutan Tsukihime", episode_count: 12, show_type: "TV"},
  {title: "Sola", episode_count: 13, show_type: "TV"},
  {title: "Soul Eater", episode_count: 51, show_type: "TV"},
  {title: "Steins;Gate", episode_count: 25, show_type: "TV"},
  {title: "Steins;Gate: Oukoubakko no Poriomania", episode_count: 1, show_type: "Special"},
  {title: "Suisei no Gargantia", episode_count: 13, show_type: "TV"},
  {title: "Summer Wars", episode_count: 1, show_type: "Movie"},
  {title: "Suzuka", episode_count: 26, show_type: "TV"},
  {title: "Suzumiya Haruhi no Yuuutsu", episode_count: 14, show_type: "TV"},
  {title: "Sword Art Online", episode_count: 25, show_type: "TV"},
  {title: "Tales of Symphonia The Animation: Sylvarant-hen", episode_count: 4, show_type: "TV"},
  {title: "Tengen Toppa Gurren Lagann", episode_count: 27, show_type: "TV"},
  {title: "Tengen Toppa Gurren Lagann Movie: Gurren-hen", episode_count: 1, show_type: "Movie"},
  {title: "Tengen Toppa Gurren Lagann Movie: Lagann-hen", episode_count: 1, show_type: "Movie"},
  {title: "Thermae Romae", episode_count: 3, show_type: "TV"},
  {title: "Toaru Kagaku no Railgun", episode_count: 24, show_type: "TV"},
  {title: "Toaru Majutsu no Index", episode_count: 24, show_type: "TV"},
  {title: "Toki wo Kakeru Shoujo", episode_count: 1, show_type: "Movie"},
  {title: "Touhai Densetsu Akagi: Yami ni Maiorita Tensai", episode_count: 26, show_type: "TV"},
  {title: "Yahari Ore no Seishun Love Comedy wa Machigatteiru.", episode_count: 13, show_type: "TV"},
  {title: "Yoake Mae Yori Ruriiro na: Crescent Love", episode_count: 12, show_type: "TV"},
  {title: "Yuru Yuri", episode_count: 12, show_type: "TV"},
  {title: "Zero no Tsukaima", episode_count: 13, show_type: "TV"},
  {title: "Attack on Titan", episode_count: 26, show_type: "TV"},
  {title: "Serial Experiments Lain", episode_count: 13, show_type: "TV"}
])

items = ListItem.create!([
  {user_id: 1, anime_id: 1, status: "Completed", rating: 10},
  {user_id: 1, anime_id: 2, status: "Completed", rating: 10},
  {user_id: 1, anime_id: 3, status: "Completed", rating: 9},
  {user_id: 1, anime_id: 4, status: "Completed", rating: 9},
  {user_id: 1, anime_id: 5, status: "Plan to Watch"},
  {user_id: 1, anime_id: 6, status: "Plan to Watch"},
  {user_id: 1, anime_id: 7, status: "Plan to Watch"},
  {user_id: 1, anime_id: 8, status: "Completed", rating: 10},
])